### ISSUE TITLE
Simulation samples can save prior to their parent instance saving, resulting in the sample never starting

### ISSUE THREAD

**Issue by TheAfroOfDoom** [TheAfroOfDoom/abseir#10]
In seemingly rare circumstances, simulation samples can save before their parent simulation instance finishes saving - ~this would never happen with actual simulation occurring, but~ it results in an API error (which causes the actual simulation to not run, since a new sample row is created prior to starting the simulation).

It may have to do with the fact that samples run on separate threads to the main thread in which an instance is saved. But this doesn't seem correct, as the main thread creates an instance *before* it starts the thread which eventually runs samples.

```python
# Ensure instance parameters are valid
instance_serializer = InstanceCreateSerializer(data=data)
instance_serializer.is_valid(raise_exception=True)

# Save new simulation instance
instance = instance_serializer.save()

# Re-append parameter-parameters to instance serializer data
instance_serializer.data["parameters"] = parameters
headers = self.get_success_headers(instance_serializer.data)

# Start running simulation asynchronously
instance_thread = threading.Thread(
    target=simulate_instance,
    args=[instance, InstanceSerializer(data=data)],
    daemon=True,
)
instance_thread.start()
```

Error:
```
[21/Jul/2022 05:54:12] "POST /api/v1/simulations/instances HTTP/1.1" 201 163
Exception in thread Thread-9:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.9/threading.py", line 917, in run  
    self._target(*self._args, **self._kwargs)
  File "/backend/src/api/simulations/jobs.py", line 97, in simulate_instance
    InstanceSamples(instance, serializer)
  File "/backend/src/api/simulations/jobs.py", line 34, in __init__
    self._generate_samples()
  File "/backend/src/api/simulations/jobs.py", line 40, in _generate_samples
    sample_serializer.is_valid(raise_exception=True)
  File "/backend/src/api/simulations/serializers.py", line 37, in is_valid
    return super().is_valid(raise_exception)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/serializers.py", line 235, in is_valid
    raise ValidationError(self.errors)
rest_framework.exceptions.ValidationError: {'instance': [ErrorDetail(string='Invalid pk "4f1bad3c-8c40-42a5-a288-39bcc5baa412" - object does not exist.', code='does_not_exist')]}
```

**Comment by TheAfroOfDoom** [comment]
TODO: try removing instance thread indirection - only have extra threads for samples
